name: Daily Reminder Commit

on:
  schedule:
    - cron: "30 10 * * *"  # Runs daily at 10:30 UTC
  workflow_dispatch:       # manual run, should be ok for now

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run the bot
        run: python reminder_bot.py

      - name: Commit and push changes
        run: |
          git config --global user.name "reminder-bot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "Daily reminder update"
          git push
