name: Daily Reminder Commit

on:
  schedule:
    - cron: "30 10 * * *"  # every day at 10:30 UTC
  workflow_dispatch:

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}  # <<< THIS is crucial!

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run the bot
        run: python reminder_bot.py

      - name: Commit and push changes
        run: |
          git config user.name "reminder-bot"
          git config user.email "bot@example.com"
          git add .
          git commit -m "Daily reminder update" || echo "No changes to commit"
          git push
