name: Daily Reminder Commit

on:
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repo with PAT
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git clone https://x-access-token:${TOKEN}@github.com/${{ github.repository }} repo
          cd repo
          echo "Cloned successfully!"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run the bot
        working-directory: ./repo
        run: python reminder_bot.py

      - name: Commit and push changes
        working-directory: ./repo
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "sunjogthind"
          git config user.email "your-noreply@users.noreply.github.com"
          git add .
          git commit -m "Daily reminder update" || echo "No changes"
          git push origin main
